github:
  features:
  # Enable issue management
    issues: true
  # Enable projects for project management boards
    projects: true
# Set up mailing list notifications
notifications:
  commits:             commits@openoffice.apache.org
  